# Generated by Django 5.1.1 on 2024-09-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediconnect_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=255)),
                ('Patient_ID', models.CharField(max_length=255)),
                ('Breakfast_time', models.TimeField()),
                ('Lunch_time', models.TimeField()),
                ('Dinner_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.hospital'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Session_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.session'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Token_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.queue', to_field='Token_no'),
        ),
        migrations.AlterField(
            model_name='docrecord',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.doctor'),
        ),
        migrations.AlterField(
            model_name='docrecord',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='User_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.hospital'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.patient'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Prescription_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.prescription'),
        ),
        migrations.AlterField(
            model_name='noteuser',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.user'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='User_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.user'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='Medicine_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mediconnect_app.medicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Session_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.session'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.patient'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='Queue_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mediconnect_app.queuedochos'),
        ),
        migrations.AlterField(
            model_name='queuedochos',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.doctor'),
        ),
        migrations.AlterField(
            model_name='queuedochos',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.hospital'),
        ),
        migrations.AlterField(
            model_name='report',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.patient'),
        ),
        migrations.AlterField(
            model_name='report',
            name='Prescription_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.prescription'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.doctor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Hospital_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.hospital'),
        ),
        migrations.AlterField(
            model_name='session',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.doctor'),
        ),
        migrations.AlterField(
            model_name='session',
            name='Patient_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediconnect_app.patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
